name: My Second Workflow
run-name: Run-${{ github.run_id }} by ${{ github.actor }}
on: 
  push: 
    branches:
      - main
      - devlop
jobs: 
  My_First_Job:
    name: My First Job
    # continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: My First step
        continue-on-error: true
        run: |
          echo "My First Job Run Successful"
          echo "Run Id: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}
          echo "My application name is ${{ vars.app_name }} run in ${{ vars.environment }} & run By ${{ vars.team }}"
  My_Second_Job:
    name: My Second Job 
    runs-on: ubuntu-latest
    needs: My_First_Job
    steps:
      - name: My Second Job
        run: echo "My Second Job Run Successful"
